# Generated by Django 5.1.7 on 2025-04-23 03:03

import api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("saldo", models.FloatField()),
                ("usuario", models.CharField(max_length=30)),
                ("contrasena", models.CharField(max_length=128)),
                ("foto", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id_empleado", models.AutoField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(max_length=30)),
                ("contrasena", models.CharField(max_length=128)),
                ("nombres", models.CharField(default="Sin nombres", max_length=128)),
                (
                    "apellidos",
                    models.CharField(default="Sin apellidos", max_length=128),
                ),
                ("rol", models.CharField(default="Sin rol", max_length=128)),
                ("foto", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                ("id_estado", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.CharField(default="por preparar", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Motivo",
            fields=[
                ("id_motivo", models.AutoField(primary_key=True, serialize=False)),
                ("motivo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Palomitas",
            fields=[
                ("id_palomitas", models.AutoField(primary_key=True, serialize=False)),
                ("precio", models.FloatField()),
                ("tamano", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Palomitera",
            fields=[
                ("id_palomitera", models.AutoField(primary_key=True, serialize=False)),
                ("ubicacion", models.CharField(max_length=200)),
                ("cantidad_palomitas", models.FloatField()),
                ("cantidad_granos", models.FloatField()),
                ("estatus", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codigo_verificacion",
                    models.IntegerField(
                        default=api.models.generar_codigo_verificacion, unique=True
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("monto_pagado", models.FloatField(blank=True, null=True)),
                ("cambio", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cliente",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empleado",
                    ),
                ),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.estado",
                    ),
                ),
                (
                    "motivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.motivo",
                    ),
                ),
                (
                    "palomitas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.palomitas"
                    ),
                ),
                (
                    "palomitera",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.palomitera",
                    ),
                ),
            ],
        ),
    ]
